---
- apt: update_cache=yes cache_valid_time=3600
- name: tomcat
  apt: name={{ item }} state=present
  with_items:
    - default-jdk
    - apache2
    - tomcat8
    - tomcat8-admin
    - libmysql-java
